os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
script:
- mvn install
before_install:
- bash .util/build_xatkit.sh
notifications:
  slack:
    secure: bESqs2fVSimwh81qza0NKubpAMQmE065EJDdRcNwFreHE2NCOkz5PofJaKrqTiv3AsL+CXN3YTQ0IrWSKSzmabNRtWONW1MOqv5lTgndIDk1H1CPsipw5saOZ95P9thcszhd15H/5VR9pcvkTyGhCaHq4ZxFITMIJqoGUMP9aY6EeVXObLLaB/WKtsTAAL+6z7cAEax0MOjzzU3Y+kqvazFAlRUfu8NgUCVAlHFCHEYmT4Rb3e7REKT0XArwIrj8mjRWjlkr/xINNeTyH3SElkFVmSyglaNJm5QkobN2X8Ck4GNMCE8eR3UHl1q3+eGWCsy+pKoXEIrI4EvyCNO+rE6+F08Cvrflp1kMsXUQdVgRpHB/qNwqH8E2Z4Y/8nUXzQKfYp9CLoelUIRj2Q1nh31Do7hS4xodyCOgOdWg3a0d0UGM09kpSUGOGDVOyOKd2R0zwW3lWiqg6WUiQ03ra4ps2Kk6TnYsY10mnc/XtBoC2DtB30sa7t7Ja8Y0BWr8p+hz1KjZ04uXex7vJ79Fe+/4r0q51/XizHUTa3GD5Nms0ArA4nFKM+fmFH2Z0vC7Zt5efFnxPo8VpSL51dGFHbYiZ+3IoGHE36uGOF/6fXeRWIrgY07CahsviGAIBuaYJ3M+T1qM4VQttxrJ4bMCagNy22UH00m4aWGSoNyJwP0=
